### ISSUE TITLE
Support collecting data through HAProxy socket

### ISSUE THREAD

**Issue by Mesverrum** [newrelic/nri-haproxy#53]
## Is your feature request related to a problem? Please describe.
For security reasons and to align with their existing setup some customers prefer not to enable the stats page and would like to be able to monitor HAProxy via the socket connection

## Feature Description
Config option to collect info via the socket instead of stats page

## Additional context
This mode is supported by most of our competitors and is considered to be the "standard" way to do this for scripts and monitoring solutions.

## Priority
Nice to Have

**Comment by thejml** [comment]
If this isn't going to be done anytime soon, your documentation should be updated to explicitly state that the stats page only works over http/https and must not be a socket. At least then it would be clear what the users are supposed to do to enable their statistics to be gathered.
