### ISSUE TITLE
`haproxyClusterName` is not translated to DM format

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-haproxy#56]
## Description

In #29 we introduced the `haproxyClusterName` attribute, but it was never added to spec files. Therefore, customers using metric queries will not be able to access it.

We should add it to the spec file and shim it as `haproxy.clusterName`.

Thanks @jlegoff for noticing this!

**Comment by gsanchezgavier** [comment]
https://source.datanerd.us/infrastructure/infra-integration-specs/pull/279
