### ISSUE TITLE
[ERR] Must supply a cluster name to identify this HAProxy instance as of 2.0.0

### ISSUE THREAD

**Issue by foozmeat** [newrelic/nri-haproxy#6]
* My YAML config file matches the format of the example in this repo
* There's no mention of a cluster name at https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/haproxy-monitoring-integration

I guessed at adding a `cluster_name` entry to my YAML config file and it appears to work so hey lucky me! Do I get a discount on my next bill for fixing this myself?

**Comment by ccheek21** [comment]
@foozmeat Thanks for the bug report. Looks like the docs changes got missed on this one! Unfortunately, the power of giving discounts doesn't lie in my hands :)

**Comment by ccheek21** [comment]
Fixed by #8f64

**Comment by ccheek21** [comment]
Docs updates coming shortly
